# Generated by Django 4.2.2 on 2023-06-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0004_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'replies'},
        ),
    ]
