# Generated by Django 4.2.2 on 2023-06-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0005_alter_reply_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='poster',
            new_name='replier',
        ),
    ]
