# Generated by Django 4.2.2 on 2023-06-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0006_rename_poster_reply_replier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replier',
        ),
    ]
